### ISSUE TITLE
Metronome goes Fruityloops? :D

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer_metronome#1]
I just saw: https://www.youtube.com/shorts/F4xu13y0wTM

Many years ago, I think when I was still on windows, I found
fruity loops. I always wanted to create music via the computer,
even had piano when I was a kid, but I am way too impatient
to follow through with it.

Looking at the metronome go, it did, for an awkward reason,
remind me of fruityloops.

https://i.imgur.com/8WKZSTS.jpg

I guess such a GUI is neither in scope of metronome, and
takes too much time. But who knows, perhaps in some years
creating such GUIs would be super-easy, like via glimmer,
or perhaps glimmer-AI - the AI that writes the GUIs for
you! :)

Anyway, just had to mention it. You probably spent quite 
some time learning how to drum in sync. I liked Phil 
Collins when he was younger in how he hit the drums.

**Comment by AndyObtiva** [comment]
Fruity Loops can certainly be built using Glimmer DSL for SWT or Glimmer DSL for LibUI by dividing and conquering the user interface into custom widgets/controls/shapes (view components), and composing them of each other while binding each view component to presenters and models behind the scenes that handle all the logic. 

The problem can be tackled as one feature at a time until an application like Fruity Loops is complete. I bet it cost its company years and millions of dollars to build that app. I bet it would take a fraction of the time and resources to build that app with a Glimmer GUI library. Probably 2% of the time, cost, and effort. 

Anyways, Glimmer Metronome is limited to being a metronome, but I do have plans for expanding its features to support storing metronome settings for set lists of songs while being able to vary the metronome tempo and beat count in the middle of a song depending on each song section. 

I am closing this issue just because it doesn’t specify any exact metronome features to add. 

But, thank you for the kind comment about my drumming.
